export const pets = [
  {
    id: 1,
    name: "Tuffy",
    category: "Dog",
    breed: "German Shepherd",
    // precautions: "these are the precatuions",
    // interests: "these are the interests of the dog",
    from: "15/01/2023",
    to: "15/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
  {
    id: 1,
    name: "Tuffy",
    category: "Dog",
    breed: "German Shepherd",
    from: "15/01/2023",
    to: "15/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
  {
    id: 1,
    name: "Tuffy",
    category: "Dog",
    breed: "German Shepherd",
    from: "15/01/2023",
    to: "15/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
  {
    id: 1,
    name: "Tuffy",
    category: "Dog",
    breed: "German Shepherd",
    from: "15/01/2023",
    to: "15/01/2023",
  },
  {
    id: 2,
    name: "Snowball",
    category: "Cat",
    breed: "Fluffy",
    from: "31/01/2023",
    to: "01/01/2023",
  },
];

export const userPets = [
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    category: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    category: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    category: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    category: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    category: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    category: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
];

export const petBreeds = {
  Cat: [
    "Ragdoll",
    "Sphynx",
    "Maine Coon",
    "Abyssinian",
    "Siamese",
    "Persian",
    "British Shorthair",
  ],
  Dog: [
    "Labrador Retriever",
    "Husky",
    "Bulldog",
    "Poodle",
    "German Shepherd",
    "Golden Retriever",
    "Beagle",
  ],
  Rabbit: [
    "Mini Lop",
    "Rex",
    "Lionhead",
    "Flemish Giant",
    "Dutch",
    "Holland Lop",
    "English Angora",
  ],
  Fish: [
    "Goldfish",
    "Betta",
    "Angelfish",
    "Guppy",
    "Cichlid",
    "Tetra",
    "Molly",
  ],
  Bird: [
    "Parakeet",
    "Cockatiel",
    "Canary",
    "Finch",
    "Lovebird",
    "African Grey Parrot",
    "Cockatoo",
  ],
  Reptile: [
    "Ball Python",
    "Corn Snake",
    "Bearded Dragon",
    "Leopard Gecko",
    "Iguana",
    "Turtle",
    "Chameleon",
  ],
};
